### ISSUE TITLE
Github Action Failing When Merging Forks

### ISSUE THREAD

**Issue by d-ryan-ashcraft** [TechnologyBrewery/poetry-monorepo-dependency-plugin#14]
When merging a fork, the project's github action is failing with the following error:
```
Run advanced-security/maven-dependency-submission-action@v3
depgraph-maven-plugin:reactor
depgraph-maven-plugin:aggregate
Dependency Snapshot
Submitting Snapshot...
Notice: Submitting snapshot...
Notice: {
    "detector": {
        "name": "maven-dependency-tree-action",
        "url": "https://github.com/advanced-security/maven-dependency-tree-action",
        "version": "3.0.3"
    },
    "version": 0,
    "job": {
        "correlator": "build",
        "id": "7396913477"
    },
    "sha": "db10a5720660cb6035ac6a937be4fa1a[12](https://github.com/TechnologyBrewery/poetry-monorepo-dependency-plugin/actions/runs/7396913477/job/20123556484#step:7:13)113754",
    "ref": "refs/pull/10/merge",
    "scanned": "2024-01-03T12:15:04.253Z",
    "manifests": {
        "poetry-monorepo-dependency-plugin": {
            "resolved": {},
            "name": "poetry-monorepo-dependency-plugin",
            "file": {
                "source_location": "pom.xml"
            }
        }
    }
}
Error: HTTP Status 403 for request POST https://api.github.com/repos/TechnologyBrewery/poetry-monorepo-dependency-plugin/dependency-graph/snapshots
Error: Response body:
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/dependency-graph/dependency-submission#create-a-snapshot-of-dependencies-for-a-repository"
}
Error: Resource not accessible by integration
Error: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/advanced-security/maven-dependency-submission-action/v3/node_modules/@github/dependency-submission-toolkit/dist/index.js:4776:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

/home/runner/work/_actions/advanced-security/maven-dependency-submission-action/v3/node_modules/@github/dependency-submission-toolkit/dist/index.js:396
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
^
Error: Failed to submit snapshot: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/advanced-security/maven-dependency-submission-action/v3/node_modules/@github/dependency-submission-toolkit/dist/index.js:520:1
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/advanced-security/maven-dependency-submission-action/v3/node_modules/@github/dependency-submission-toolkit/dist/index.js:396:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by d-ryan-ashcraft** [comment]
Recreated by forking in my own personal repository

**Comment by d-ryan-ashcraft** [comment]
Resolved by updating the [github action to use `pull_request_target` rather than `pull_request'](https://github.com/advanced-security/maven-dependency-submission-action/issues/55).
